version: '3.9'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=your_bot_token_here
      - OPENAI_API_KEY=your_openai_key_here
      - DATABASE_URL=postgres://user:pass@postgres:5432/caloriebot
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: ["cargo", "run"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: caloriebot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pg_data:
